language: node_js
node_js:
  - "stable"

cache: npm

install:
  - npm install

script:
  - npm run coveralls

after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: patrickmitchell87@icloud.com
  name: Mitchell Patrick
  keep_history: true
  allow_empty_commit: false
  verbose: true
  on:
    branch: test